---
# tasks file for fedora-desktop
  - name: Install all the applications. 
    block:

      - name: install rpmfusion free
        dnf:
          name: "{{ rpmfusion_free }}"
          state: installed

      - name: install rpmfusion nonfree
        dnf:
          name: "{{ rpmfusion_nonfree }}"
          state: installed

      - name: Install all the cool apps
        dnf: 
          name: "{{ dnf_software }}" 
          state: installed

      - name: Download oh-my-zsh install.sh
        get_url: 
          url: "{{ ohmyzsh_install }}" 
          dest: "{{ home_user }}"  
          mode: 755

      - name: run the install.sh
        script: "{{ home_user }}install.sh"
        creates: "{{ home_user }}.oh-my-zsh"

      - name: create the font dir
        file:
          state: directory
          path: "{{ home_user }}"./local/share/fonts/NerdFonts

      - name: Copy the theme over to the home directory
        git:
          repo: "https://github.com/bhilburn/powerlevel9k.git"
          dest: "{{ home_user }}.oh-my-zsh/custom/themes/powerlevel9k"


  - name: install the dev rpms and require repo's
    dnf:
      name: "{{ fedora_gaming.dev_rpms }}"
      state: install
    when: dev_rpms
  - name: install the gaming rpms
    dnf:
      name: "{{ fedora_gaming.gaming }}"
      state: install
    when: gaming_rpms

  - name: install all the dolphin-emu required rpms
    dnf:
      name: "{{ fedora_gaming.dolphin_emu }}"
      state: install
    when: dolphin_emu

  - name: install all the rpcs3 required rpms
    dnf:
      name: "{{ fedora_gaming.rpcs3 }}"
      state: install
    when: rpcs3