---
# tasks file for fedora-desktop
  - block:

      - name: install rpmfusion free
        dnf:
          name: "{{ rpmfusion_free }}"
          state: installed

      - name: install rpmfusion nonfree
        dnf:
          name: "{{ rpmfusion_nonfree }}"
          state: installed

      - name: Install all the cool apps
        dnf: 
          name: "{{ dnf_software }}" 
          state: installed

      - name: Download oh-my-zsh install.sh
        get_url: 
          url: "{{ ohmyzsh_install }}" 
          dest: "{{ home_user }}"  
          mode: 755

      - name: run the install.sh
        script: "{{ home_user }}install.sh"
        creates: "{{ home_user }}.oh-my-zsh"

      - name: create the font dir
        file:
          state: directory
          path: "{{ home_user }}"./local/share/fonts/NerdFonts

      - name: "copy powerlevel9k to your home dir"
        git:
          repo: "https://github.com/bhilburn/powerlevel9k.git"
          dest: "{{ home_user }}.oh-my-zsh/custom/themes/powerlevel9k"


